### ISSUE TITLE
How to recover bricked board?

### ISSUE THREAD

**Issue by mkschreder** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#10]
I have managed to brick the board and I'm now trying to burn a new image to it through recovery console. You have mentioned that you have used the console to burn a new image. How did you do it? This was after I have burned your basic image (which worked fine until I wanted to run sysupgrade again and messed it up). 

From what I can tell, the console I have is far inferior to modern uboot. I have not even managed to get tftp working. It just tells me that arp has timed out etc. Commands like cp.b are also missing. I have cp.linux but it doesn't work (giving a garbage size when i do it after uploading image). What address should I upload it to? 

Do you know where I can get a working version of uboot and do you know how to flash it? What address do I load it into? How do I permanently flash it to spi flash? 

RT5350 # version

U-Boot 1.1.3 (Sep  1 2012 - 08:34:08)

RT5350 # loadb 3000
.. load uboot256.bin image with kermit 

RT5350 # bootm 3000
Booting image at 00003000 ...
   Image Name:   SPI Flash Image
   Created:      2014-01-09   9:10:07 UTC
   Image Type:   MIPS Linux Standalone Program (uncompressed)
   Data Size:    105456 Bytes = 103 kB
   Load Address: 80200000
   Entry Point:  80200000
   Verifying Checksum ... OK
OK
(hang) 

This is as far as I have gotten so far. Any help would be appreciated. :)

Can I use any of your images and load it like this?

**Comment by mkschreder** [comment]
I tried loading openwrt-ramips-rt305x-uImage.bin but no luck so far. 

RT5350 # load
Ready for binary (kermit) download to 0x80100000 at 57600 bps...

(/) C-Kermit>send /tftpboot/openwrt-ramips-rt305x-uImage.bin 
(/) C-Kermit>c
Connecting to /dev/ttyUSB3, speed 57600
 Escape character: Ctrl-\ (ASCII 28, FS): enabled
Type the escape character followed by C to get back, or followed by ? to see other options.
Total Size      = 0x001090df = 1085663 Bytes
Start Addr      = 0x80100000
RT5350 # boot
Booting image at 80100000 ...
   Image Name:   MIPS OpenWrt Linux-3.18.14
   Created:      2015-09-02   9:13:46 UTC
   Image Type:   MIPS Linux Kernel Image (lzma compressed)
   Data Size:    1085599 Bytes =  1 MB
   Load Address: 80000000
   Entry Point:  80000000
   Verifying Checksum ... OK
   Uncompressing Kernel Image ... LZMA ERROR 1 - must RESET board to recover

(reboot)

**Comment by wingspinner** [comment]
If you read the instructions I wrote in the first few posts of that thread it’s all there.

Cheers,
Ron

**Comment by mkschreder** [comment]
Well, you don't say much about HOW to do it. I looked at several other examples of flashing similar boards but I could not make the same commands work with the version of uboot from your basic image (which is what I flashed before). 

"If you have at least average soldering skills you can  solder a 3v USB<->Serial cable to the board, setup a tftp server and replace it using tftp, then reboot and use that to  burn the OpenWRT sysupgrade image to the correct MTD partition using tftp. That's how I did it the first time."

I was able to flash uboot image over serial but tftp is still not working. my tftp does work from a different host on the network though. 

Have you had this problem before: 

System Load Linux Kernel then write to Flash via TFTP. 
 Warning!! Erase Linux in Flash then burn new one. Are you sure?(Y/N)
 Please Input new ones /or Ctrl-C to discard
        Input device IP (192.168.1.8) ==:192.168.1.1
        Input server IP (192.168.1.112) ==:192.168.1.100
        Input Linux Kernel filename () ==:linux.bin

 netboot_common, argc= 3 

 NetTxPacket = 0x81FE6500 

 KSEG1ADDR(NetTxPacket) = 0xA1FE6500 

 NetLoop,call eth_halt ! 

 NetLoop,call eth_init ! 
Trying Eth0 (10/100-M)

 Waitting for RX_DMA_BUSY status Start... done

 Header Payload scatter function is Disable !! 

 ETH_STATE_ACTIVE!! 
Using Eth0 (10/100-M) device
TFTP from server 192.168.1.100; our IP address is 192.168.1.1
Filename 'linux.bin'.

 TIMEOUT_COUNT=10,Load address: 0x80100000
Loading: *
ArpTimeoutCheck 
T T T T T T T T T T

**Comment by mkschreder** [comment]
Could this be some kind of ethernet duplex/half duplex mismatch issue?

**Comment by wingspinner** [comment]
Best place to go for these kinds of issues is the openwrt.org site and forum. Lot's of info on uboot and similar questions and answers regarding rt5350.
