### ISSUE TITLE
opkg binaries fail to run

### ISSUE THREAD

**Issue by thesandlord** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#11]
Hi,

With the "Factory Image (WS)" in the repo, it looks like the Chaos Calmer binaries that opkg pulls down no longer work. Ash keeps saying "not found" for basically every binary I try to run (not all). I think they might use a different libc like musl or something like that (I'm a complete newb to OpenWRT, but doing some research that seems to be the core reason)

Upgrading to the latest stable (15.05, r46767) solves all these issues. Is there a plan to update the "Factory Images" in this repo to use this build?

[Here is the sysupgrade image, as found on the OpenWRT site](http://downloads.openwrt.org/chaos_calmer/15.05/ramips/rt305x/openwrt-15.05-ramips-rt305x-ht-tm02-squashfs-sysupgrade.bin). It works great, but I had to manually upgrade.

If you don't want to create the image, I can send you a pull request. I just have to learn how to use your tool that creates the images. (However I have no way to test it because I don't know how to flash back to stock)

**Comment by JonasWilms** [comment]
As wingspinner said in [README.md](https://github.com/wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT/blob/master/README.md)

> I've found revision r42649 to be very stable so upgrading to the latest trunk revision isn't necessarily a  requirement and opkg can be configured to download packages from [r42649](https://github.com/wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT/tree/master/ramips_openwrt/packages-r42649).

**Comment by wingspinner** [comment]
If you can generate updated images I'm all for it!
