### ISSUE TITLE
Android usb tethering to HooToo TM02 openwrt

### ISSUE THREAD

**Issue by mikekornikh** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#12]
Hello! I've successfully installed openwrt on the tripmate nano but can't seem to get it to talk to my android phone when i set it to usb tether. I've tried creating different interfaces and following a few guides like these...
https://wiki.openwrt.org/doc/howto/usb.tethering
http://lgallardo.com/en/2011/05/26/usando-el-anclaje-de-red-tethering-de-android-en-openwrt/
...with no success. I was able to connect the hootoo to a wifi as a client in case it needed to download a package. Any advise?

**Comment by JonasWilms** [comment]
You have to use packages matching to your version, 
https://github.com/wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT/tree/master/ramips_openwrt
