### ISSUE TITLE
Can't access failsafe mode

### ISSUE THREAD

**Issue by Cabalist** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#13]
Hello,  

I've followed the steps and flashed with `openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r44945-basic.bin`.  The system was working and while I was setting it up with relayd made a typo in my /etc/config/wireless.   To correct this I am trying to load the device into failsafe more.

I hold the reset button when the lights are flashing and get the familiar fast flash but I am unable to connect to (or ping) 192.168.1.1.  I have my computer setup with:

IP: 192.168.1.2 
Subnet mask: 255.255.255.0
Gateway: 192.168.1.1

I have 3 or 4 of the HooToo Tripmate Nanos and have confirmed when setting them into failsafe I cannot access 192.168.1.1   Is there another address that has been set?  Am I missing a step?

**Comment by wingspinner** [comment]
I’ve never used the failsafe. In fact, I don’t even know if it’s compiled int to that binary.  Sorry, can’t offer much help there.

Regards,
Ron

**Comment by Cabalist** [comment]
Thanks Ron.  I got around it using TFTP recovery.  Steps below in case anyone searches for this in the future:

Requires a TFTP server running on your machine.

You need to do the following steps to reflash the firmware.  

Start with the firmware you had originally loaded.  For our example we will use `openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r44945-ws.bin`
1. Convert .bin to .tar.gz archive `tail -n +166 openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r44945-ws.bin > openwrt.tar.gz`
2. Extract the files inside.  You should see `firmware.bin` and `uboot.bin`
3. Rename `firmware.bin` to `Kernal.bin`.   (Yes.  `Kernal.bin` Spelling and capitalization count.)
4. Move `Kernal.bin` to your TFTP directory
5. Set your computer to have IP address 10.10.10.3 with subnet mask 255.255.255.0
6. Power off the router.
7. Connect ethernet cable
8. Press and hold router reset pin with paper clip.  While holding reset plug power in.
9.  Wifi LED should light up then go out again, 3-5 seconds.  Continue holding reset for another 10-15 seconds.  
10. It can take another 3-5 minutes for the firmware to install.  Let it sit for a while, up to 10 minutes, then power cycle the router.  It should boot up on default config for OpenWRT.

**Comment by frakman1** [comment]
Thank you Cabalist! Your instructions saved my life! 
My experience was that it took about 20 seconds from the time I powered it up with the Reset button pressed before the TFTP download started.
