### ISSUE TITLE
Firmware Upgrade image is in Wrong Format

### ISSUE THREAD

**Issue by frakman1** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#16]
When I tried using the image "openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r44945-ws.bin" to upgrade the firmware through the stock image's System's Firmware upgrade menu, it said that the image was in the wrong format. I had to use "openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r42649.bin". Only that one was accepted.

**Comment by ghost** [comment]
I have this issue with every firmware you've provided. TripMate says it's the wrong format. openwrt-ramips-rt305x-ht-tm02-squashfs-factory-r42649.bin does not work as of September 2018. Attempted upgrade with OE firmware 2.000.046.
