### ISSUE TITLE
Build image including USB serial patches

### ISSUE THREAD

**Issue by frakman1** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#17]
Can you please provide an upgrade image (for openwrt) that incudes the patches you provided? I don't have a way to make a build from scratch and would REALLY love to get the feature that lets me use the USB as a serial device to capture serial logs from another device. Your help would be greatly appreciated. Thank you for putting this page together as it has helped me tremendously so far.

**Comment by JonasWilms** [comment]
You can get the tm02 build (which contains the patch) from the official download page

This is the latest Chaos Calmer Release
http://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/openwrt-15.05.1-ramips-rt305x-ht-tm02-squashfs-sysupgrade.bin

**Comment by frakman1** [comment]
Great. Thank you.
I can see the USB serial cable populate as /dev/ttyUSB! What command line tool can I use in openwrt that would read it? I don't see 'screen' or 'minicom' equivalent anywhere.

**Comment by JonasWilms** [comment]
There should be packages for both minicom and screen, Try to install them using 
`opkg install screen` or `opkg install minicom`.

 If you dont have an internet connection, move the .ipk files to your device and install them locally.

https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/packages/packages/minicom_2.7-1_ramips_24kec.ipk
https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/packages/packages/screen_4.3.1-1_ramips_24kec.ipk

**Comment by frakman1** [comment]
I have a strange problem. Although it installs the package(s). When I try to run them, it says "xxx not found". 

> Installing screen (4.3.1-1) to root...
> Downloading http://downloads.openwrt.org/snapshots/trunk/ramips/generic/packages/packages/screen_4.3.1-1_ramips_24kec.ipk.
> Configuring screen.
> root@OpenWrt:/sys/kernel/debug/usb# screen
> -ash: screen: not found
> root@OpenWrt:/sys/kernel/debug/usb# which screen
> /usr/sbin/screen
> root@OpenWrt:/sys/kernel/debug/usb# /usr/sbin/screen
> -ash: /usr/sbin/screen: not found

**Comment by frakman1** [comment]
Nevermind, I installed your image and it behaves properly now.
Thank you so much!

**Comment by frakman1** [comment]
Sorry for all the questions, but with the new firmware, it is missing all the usb-serial packages that I saw when I did a 'opkg list | grep serial'. I know I didn't install them manually so where do I go to get them all?
Is there a set of usb-serial packages I need to install manually?

**Comment by JonasWilms** [comment]
The packages included in the original wingspinner build are

> ```
>    wpad-mini \ kmod-ledtrig-netdev kmod-ledtrig-timer kmod-leds-gpio kmod-ledtrig-default-on \ kmod-usb-core kmod-usb-ohci kmod-usb2 kmod-usb-net usbutils \ kmod-scsi-core kmod-scsi-generic kmod-fs-ext4 \ kmod-usb-storage kmod-usb-storage-extras block-mount \ kmod-usb-serial kmod-usb-serial-ftdi kmod-gpio-button-hotplug \ kmod-nls-cp437 kmod-nls-iso8859-1 kmod-nls-utf8 luci luci-mod-admin-full \ kmod-app-samba luci-theme-openwrt luci-proto-relay relayd nano \ fstools
> ```

But you might need at least kmod-usb-serial and kmod-usb-serial-ftdi 

For more information have a look at https://wiki.openwrt.org/doc/hardware/port.serial

**Comment by frakman1** [comment]
Apparently mine didn't have it for some reason (I installed the firmware you linked). I ended up manually installing it this way and now it works!

> #opkg install http://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/packages/base/kmod-
> usb-serial_3.18.23-1_ramips_24kec.ipk
> 
> #opkg install http://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/rt305x/packages/base/kmod-
> usb-serial-ftdi_3.18.23-1_ramips_24kec.ipk

**Comment by JonasWilms** [comment]
The official images don't come with pre-installed packages.

**Comment by frakman1** [comment]
Do you know if it supports USB gadget mode? The reverse USB-serial case is also something I am trying to get work.

**Comment by JonasWilms** [comment]
I don't know if it works out of the box, but you might try `opkg install kmod-usb-serial-gadget`

**Comment by frakman1** [comment]
That package was not available. Nor was kmod-usb-gadget

**Comment by wingspinner** [comment]
I only have bandwidth to address questions specific to my patches. You should direct general OpenWRT questions to the OpenWRT website and forum.

Cheers,
Ron
