### ISSUE TITLE
kernel v.s. opkg kmods out of sync

### ISSUE THREAD

**Issue by tz1** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#2]
It is apparently the same issue.  Because your kernel is different (in the hash string), no new kmods will load, and it means although I have space, I can't install openvpn-openssl since it depends on a kmod that can't be downloaded.

Is there a sysupgrade in the main BB tree that will work?

**Comment by wingspinner** [comment]
This kernel is not Barrier Breaker. BB has too many bugs in the rt5350 support. This is based on the bleeding edge trunk kernel which is called "Chaos Calmer". With regards to your "kmods out of sync" issue, it's not an issue. As with all Linux kernels you must load the modules that are the same revision as your kernel (well, actually, it's a simple matter to disable this checking). The openwrt wiki is your friend. Answers to all your issues are there with some quick searching. I'll try to provide some links when I get time but as has been written by many wise men "the search function is your friend" and the search function on wiki.openwrt.org and on forums.openwrt.org will quickly provide answers.
