### ISSUE TITLE
How to get back to Stock?

### ISSUE THREAD

**Issue by EpicLPer** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#20]
Sorry if this is maybe a little offtopic but so far you're the most competent I found working on such a project.

Anyways, I want to go back to stock on my HT-TM01, since the TM02 is basically the same hardware as the 01 it should have similar instructions :)

Do you know how I could do that? When I go to their firmware download page all I get is a ".046" file which I guess is basically a image renamed.

Thanks a ton already and sorry if it's a bit offtopic to this project!

**Comment by EpicLPer** [comment]
... well okay then

**Comment by Mhowser** [comment]
can we get an answer to this please?

**Comment by EpicLPer** [comment]
Seems like the Dev is either abandoning this project or is just a d...

**Comment by Mhowser** [comment]
Well thats too bad... I was hoping to keep tinkering with my tm-02 but its soft bricked

**Comment by EpicLPer** [comment]
In case someone still reads this: https://github.com/wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT/issues/21
