### ISSUE TITLE
Can you go into further details?

### ISSUE THREAD

**Issue by supsup** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#3]
I made it to step #7, all appears to be working fine.

#7. LUCI should be up and running so browse to 192.168.1.1 and configure as needed. This install is intended as only an initial install to get openwrt on your device so the first thing you should do is upgrade using the latest trunk "upgrade" binary from openwrt.org.

I went to openwrt to look for the this latest trunk "upgrade" but it's a maze.  Any suggestions on exactly what steps to take to get to the right upgrade?

**Comment by wingspinner** [comment]
Check out the OpenWRT wiki. Lots of instructions there on how and which images to load. Take a look at the HowTo's. You'll learn a lot there.
