### ISSUE TITLE
Default root password of my Tripmate TM02 was 20080826

### ISSUE THREAD

**Issue by githufsb** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#5]
You may want to update README to indicate that the root password of Tripmate TM02 is "20080826". Also, the telnetd on mine was running already out of the box.  I found the hardware was really similar to RAVPower Filehub, and I found the root password of that one a while back via internet search.  I think these are all the same wifi soc, with very similar firmware.

**Comment by wingspinner** [comment]
All RT3053 based devices are very similar no doubt.The things that can be different that affect compatibility with a particular OpenWRT image are:
1. Firmware upgrade protocol
2. Flash type and size
3. GPIO assignments
4. Other peripheral devices that may be connected to I2C and other I/O's.

I'm aware on the root password although I've never seen on with telnet already enabled. Could it be that someone has already played with the one you have?

Cheers,
Ron
