### ISSUE TITLE
Support for HT-TM03

### ISSUE THREAD

**Issue by Manawyrm** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#8]
Hello,

I have got a HT-TM03 (the one with the 3Ah battery). 
It works fine with your software, thank you. 

The only change I had to do was the path.

Your software has the hardcoded path to /data/UsbDisk1/Volume1 in the upload script, which isn't too handy on this unit, because it features an MicroSD card reader. 
The microSD card reader always gets called /data/UsbDisk1/Volume1 
the USB drive was /data/UsbDisk2/Volume1

For me to get the upload working I just symlinked the directories over a serial line, but thats of couse not the best solution. 

I would think it would be a good idea to parse/grep through the mount-output and look for devices in the /data/ directory.

Anyway, apart from that, it seems to work nicely. Thanks,
Tobias

**Comment by wingspinner** [comment]
Tobias,

If you used a USB stick as the instructions say it would work fine. Have done many of them…..

Regards,
Ron

**Comment by Manawyrm** [comment]
I did. as I've said, there was a UsbDisk1 directory on mine already present. (no sd card inserted)

**Comment by wingspinner** [comment]
Hmmm, you're the first with a problem that I know of. 

Good luck

Ron Curry
ron@curry.org

**Comment by Manawyrm** [comment]
Actually it seems like someone in the forum also figured the same thing out...
https://forum.openwrt.org/viewtopic.php?pid=280351#p280351

**Comment by wingspinner** [comment]
Yes, there must be something slightly different in the way you are using things. I've used this on no less that 5 TM-03's without an issue. My guess is it has to do with the path specified in the HooToo software when you start the upgrade. In any case, I designed test this for the TM-02 and the fact that it works at all on the TM-03 is a bonus.
