### ISSUE TITLE
Fstab support?

### ISSUE THREAD

**Issue by coreintegrity** [wingspinner/HooToo-Tripmate-HT-TM02-OpenWRT#9]
Hello good sir. First off thank you for all of your work on this and getting openwrt supported on our Tripmates. I'm trying to get exroot setup however I'm getting "block

**Comment by coreintegrity** [comment]
(*Sry accidentally hit enter) not found" I also don't see a fstab etc/default to add entries for overlay mounting on sda1. Do I just create the fstab file and the system will pick it up?

Thank you

**Comment by wingspinner** [comment]
This is an openwrt issue which I have no involvement in. Best to check the openwrt.org site for info.
